# ~/.config/flashbackclient/scheduler/scheduler.yaml
# Default rules for the scheduler

rules:
  - id: 0
    name: "Download on startup"
    action: "download_changed"
    cases:
      - id: "on_startup"

  - id: 1
    name: "Upload on shutdown"
    action: "upload_changed"
    cases:
      - id: "on_shutdown"

  - id: 2
    name: "Sync changed files after 2 hours"
    action: "sync_files"
    cases:
      - id: "on_file_change"
      - id: "after_interval"
        file_change_trigger: true
        after_last: 120
        before_next_scheduled: 60
