# scheduler.yaml documentation
#
# This file provides the default settings for the scheduler to use

# Possible actions to take
actions:
  download_changed: "Download changed files"
  upload_changed: "Upload changed files"
  sync_files: "Download and upload changed files"
  no_action: "Take no action"

# Possible triggers to trigger an action
triggers:
  on_startup: "System startup"
  on_shutdown: "System shutdown"
  on_file_change: "After a detected file change"
  on_schedule: "Specific cron expressions"
  after_interval: "Time after any previous"

# Rules for triggering actions
rules:
  - name: "Download on startup"
    action: ${actions.download_changed}
    cases:
      - id: ${triggers.on_startup}
  
  - name: "Upload on shutdown"
    action: ${actions.upload_changed}
    cases:
      - id: ${triggers.on_shutdown}

# - name: "Sync files noon and midnight"
#   action: ${actions.sync_files}
#   cases:
#     - id: ${triggers.on_schedule}
#       times:
#         - cron_exp: "00 00 * * *"
#         - cron_exp: "00 12 * * *"

# - name: "Upload end of work week"
#   action: ${actions.upload_changed}
#   cases:
#     - id: ${triggers.on_schedule}
#       times:
#         - cron_exp: "00 17 * * FRI"

# - name: "Download start of work week"
#   action: ${actions.download_changed}
#   cases:
#     - id: ${triggers.on_schedule}
#       times:
#         - cron_exp: "00 09 * * MON"

  - name: "Sync changed files after 2 hours"
    action: ${actions.sync_files}
    cases:
      - id: ${triggers.on_file_change}
      - id: ${triggers.after_interval}
        after_last: 120
        before_next_scheduled: 60

# - name: "Download on startup on weekdays"
#   action: ${actions.download_changed}
#   cases:
#     - id: ${triggers.on_startup}
#     - id: ${triggers.on_schedule}
#       times:
#         - cron_exp: "* * * * MON-FRI"

# - name: "Upload on shutdown on weekdays"
#   action: ${actions.upload_changed}
#   cases:
#     - id: ${triggers.on_shutdown}
#     - id: ${triggers.on_schedule}
#       times:
#         - cron_exp: "* * * * MON-FRI"
