repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
#   -   id: clang-format
#       args: ["--style=file"]
#   -   id: clang-tidy
#       args: ["build/compile_commands.json"]
    -   id: cppcheck
        args: ["--enable=all", "--language=c++", "--inline-suppr",
               "--suppress=missingIncludeSystem",
               "--suppress=returnByReference", "--suppress=unusedFunction",
               "--suppress=returnByReference"]
#   -   id: include-what-you-use
#       args: ["-p", "./build/compile_commands.json"]
