# Example target file defining a target named example

name: "example"

path: "~/Dev/FlashBackClient"

target_type: "directory"

encrypt: "directory"

# Rules for triggering actions
rules:
  - id: 0
    name: "Sync files 30 minutes after last file change"
    action: "sync_files"
    cases:
      - id: "on_file_change"
      - id: "after_interval"
        file_change_trigger: true
        after_last: 30
        before_next_scheduled: 30
